/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameTableIdRouteImport } from './routes/game.$tableId'
import { Route as PortalPortalIdRouteImport } from './routes/portal.$portalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameTableIdRoute = GameTableIdRouteImport.update({
  id: '/game/$tableId',
  path: '/game/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalIdRoute = PortalPortalIdRouteImport.update({
  id: '/portal/$portalId',
  path: '/portal/$portalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game/$tableId': typeof GameTableIdRoute
  '/portal/$portalId': typeof PortalPortalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game/$tableId': typeof GameTableIdRoute
  '/portal/$portalId': typeof PortalPortalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game/$tableId': typeof GameTableIdRoute
  '/portal/$portalId': typeof PortalPortalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game/$tableId' | '/portal/$portalId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game/$tableId' | '/portal/$portalId'
  id: '__root__' | '/' | '/game/$tableId' | '/portal/$portalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameTableIdRoute: typeof GameTableIdRoute
  PortalPortalIdRoute: typeof PortalPortalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$tableId': {
      id: '/game/$tableId'
      path: '/game/$tableId'
      fullPath: '/game/$tableId'
      preLoaderRoute: typeof GameTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$portalId': {
      id: '/portal/$portalId'
      path: '/portal/$portalId'
      fullPath: '/portal/$portalId'
      preLoaderRoute: typeof PortalPortalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameTableIdRoute: GameTableIdRoute,
  PortalPortalIdRoute: PortalPortalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
