/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashoutRouteImport } from './routes/cashout'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GameTableIdRouteImport } from './routes/game.$tableId'
import { Route as PortalPortalIdRouteImport } from './routes/portal.$portalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashoutRoute = CashoutRouteImport.update({
  id: '/cashout',
  path: '/cashout',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GameTableIdRoute = GameTableIdRouteImport.update({
  id: '/game/$tableId',
  path: '/game/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalIdRoute = PortalPortalIdRouteImport.update({
  id: '/portal/$portalId',
  path: '/portal/$portalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashout': typeof CashoutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/game/$tableId': typeof GameTableIdRoute
  '/portal/$portalId': typeof PortalPortalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashout': typeof CashoutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/game/$tableId': typeof GameTableIdRoute
  '/portal/$portalId': typeof PortalPortalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashout': typeof CashoutRoute
  '/leaderboard': typeof LeaderboardRoute
  '/game/$tableId': typeof GameTableIdRoute
  '/portal/$portalId': typeof PortalPortalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cashout' | '/leaderboard' | '/game/$tableId' | '/portal/$portalId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cashout' | '/leaderboard' | '/game/$tableId' | '/portal/$portalId'
  id:
    | '__root__'
    | '/'
    | '/cashout'
    | '/leaderboard'
    | '/game/$tableId'
    | '/portal/$portalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashoutRoute: typeof CashoutRoute
  LeaderboardRoute: typeof LeaderboardRoute
  GameTableIdRoute: typeof GameTableIdRoute
  PortalPortalIdRoute: typeof PortalPortalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashout': {
      id: '/cashout'
      path: '/cashout'
      fullPath: '/cashout'
      preLoaderRoute: typeof CashoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$tableId': {
      id: '/game/$tableId'
      path: '/game/$tableId'
      fullPath: '/game/$tableId'
      preLoaderRoute: typeof GameTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$portalId': {
      id: '/portal/$portalId'
      path: '/portal/$portalId'
      fullPath: '/portal/$portalId'
      preLoaderRoute: typeof PortalPortalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashoutRoute: CashoutRoute,
  LeaderboardRoute: LeaderboardRoute,
  GameTableIdRoute: GameTableIdRoute,
  PortalPortalIdRoute: PortalPortalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
